version: '3.7'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  backend:
    container_name: backend
    command: make all
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - './backend:/app'
    ports:
      - '8080:8080'
    environment:
      - MONGO_URL=mongodb://mongo:27017/urlshortener
      - MONGO_DATABASE=urlshortener
      - MONGO_COLLECTION=urls
    links:
      - mongo

  frontend:
    container_name: frontend
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - './ui:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
