apiVersion: v1
kind: Service
metadata:
  name: url-shortener
spec:
  selector:
    app: url-shortener
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: 0xkalvin/url-shortener:latest
          env:
            - name: PORT
              value: "3000"
            - name: ENV
              value: production
            - name: GIN_MODE
              value: release
            - name: REDIS_ENDPOINT
              value: http://redis:6379
            - name: REDIS_PASSWORD
              value: 
            - name: MONGODB_USERNAME
              value: root
            - name: MONGODB_PASSWORD
              value: rootpassword
            - name: MONGODB_ENDPOINT
              value: mongo:27017
          ports:
          - name: http
            containerPort: 3000
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /_health_check
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
